/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DA.Users;
import DT.UsersDT;
import Database.DatabaseHandler;

import javax.swing.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;

public class Home extends javax.swing.JFrame {

    CardLayout layout;
    String username;
    String fullName;
    UsersDT user;
    LocalDateTime outTime;

    public Home(String username, UsersDT user) {
        initComponents();

        menuPanel.setVisible(true);
        layout = new CardLayout();
        this.username = username;
        this.user = user;

        // currentUserSession();
        // Panel Layout set to Card Layout to allow switching between different sections
        displayPanel.setLayout(layout);
        displayPanel.add("Home", new Welcome(username));
        displayPanel.add("Users", new UsersFrame());
        displayPanel.add("Products", new ProductsFrame());
        displayPanel.add("Suppliers", new SuppliersFrame());
        displayPanel.add("Purchase Order", new OrdersFrame(username));
        displayPanel.add("Purchase Records", new PRecordsFrame(this));
        displayPanel.add("Sales Records", new SRecordsFrame(this));
//        displayPanel.add("Logs", new UserLogsPage());

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                outTime = LocalDateTime.now();
                user.setOutTime(String.valueOf(outTime));
                user.setUsername(username);
//                new Users().addUserLogin(user);
                super.windowClosing(e);
            }
        });

        setTitle("Inventory Manager");
        setVisible(true);
    }

    // Methods to display different sections in the mainframe
    public void addHomeFrame() {
        layout.show(displayPanel, "Home");
    }

    public void addUsersFrame() {
        layout.show(displayPanel, "Users");
    }

    public void addOrdersFrame() {
        layout.show(displayPanel, "Purchase Order");
    }

    public void addProdFrame() {
        layout.show(displayPanel, "Products");
    }

    public void addSuppFrame() {
        layout.show(displayPanel, "Suppliers");
    }

    public void addSalesRecordsFrame() {
        layout.show(displayPanel, "Sales Records");
    }

    public void addPRecordsFrame() {
        layout.show(displayPanel, "Purchase Records");
    }

    public void addLogsPage() {
        layout.show(displayPanel, "Logs");
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 51, 51));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(50,57, 61));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        suppPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prodPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        orderPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        purchaseInfoRecordsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        usersPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        userLogsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(50, 57, 61));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suppPanel.setBackground(new java.awt.Color(50, 57, 61));
        suppPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suppPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                suppPanelMousePressed(evt);
            }
        });
        suppPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suppliers");
        suppPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 5, 60, -1));

        menuPanel.add(suppPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, -1));

        prodPanel.setBackground(new java.awt.Color(50, 57, 61));
        prodPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prodPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prodPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                prodPanelMousePressed(evt);
            }
        });
        prodPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Products");
        prodPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 5, 60, -1));

        menuPanel.add(prodPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, -1));

        orderPanel.setBackground(new java.awt.Color(50, 57, 61));
        orderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderPanelMousePressed(evt);
            }
        });
        orderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Purchase Order");
        orderPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 5, -1, -1));

        menuPanel.add(orderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 150, -1));

        purchaseInfoRecordsPanel.setBackground(new java.awt.Color(50, 57, 61));
        purchaseInfoRecordsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purchaseInfoRecordsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                purchaseInfoRecordsPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                purchaseInfoRecordsPanelMousePressed(evt);
            }
        });
        purchaseInfoRecordsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Records");
        purchaseInfoRecordsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 5, 90, -1));

        menuPanel.add(purchaseInfoRecordsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, -1));

        usersPanel.setBackground(new java.awt.Color(50, 57, 61));
        usersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usersPanelMousePressed(evt);
            }
        });
        usersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Users");
        usersPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 5, 50, -1));

        menuPanel.add(usersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 150, -1));

        userLogsPanel.setBackground(new java.awt.Color(50, 57, 61));
        userLogsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userLogsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userLogsPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userLogsPanelMousePressed(evt);
            }
        });
        userLogsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("User Logs");
        userLogsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 5, -1, -1));

        menuPanel.add(userLogsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 150, -1));

        homePanel.setBackground(new java.awt.Color(50, 57, 61));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homePanelMouseExited(evt);
            }
        });
        homePanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                homePanelKeyPressed(evt);
            }
        });
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-home-24.png"))); // NOI18N
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 30, 30));

        menuPanel.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 30));

        jPanel1.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 600));

        displayPanel.setBackground(new java.awt.Color(255, 255, 240));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(displayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 900, 510));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suppPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppPanelMousePressed
        addSuppFrame();
    }//GEN-LAST:event_suppPanelMousePressed

    private void suppPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppPanelMouseEntered
        setColor(suppPanel);
    }//GEN-LAST:event_suppPanelMouseEntered

    private void suppPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppPanelMouseExited
        resetColor(suppPanel);
    }//GEN-LAST:event_suppPanelMouseExited

    private void prodPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodPanelMouseEntered
        setColor(prodPanel);
    }//GEN-LAST:event_prodPanelMouseEntered

    private void prodPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodPanelMouseExited
        resetColor(prodPanel);
    }//GEN-LAST:event_prodPanelMouseExited

    private void prodPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodPanelMousePressed
        addProdFrame();
    }//GEN-LAST:event_prodPanelMousePressed

    private void orderPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanelMouseEntered
        setColor(orderPanel);
    }//GEN-LAST:event_orderPanelMouseEntered

    private void orderPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanelMouseExited
        resetColor(orderPanel);
    }//GEN-LAST:event_orderPanelMouseExited

    private void orderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderPanelMousePressed
        addOrdersFrame();
    }//GEN-LAST:event_orderPanelMousePressed

    private void purchaseInfoRecordsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseInfoRecordsPanelMouseEntered
        setColor(purchaseInfoRecordsPanel);
    }//GEN-LAST:event_purchaseInfoRecordsPanelMouseEntered

    private void purchaseInfoRecordsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseInfoRecordsPanelMouseExited
        resetColor(purchaseInfoRecordsPanel);
    }//GEN-LAST:event_purchaseInfoRecordsPanelMouseExited

    private void purchaseInfoRecordsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseInfoRecordsPanelMousePressed
        addPRecordsFrame();
    }//GEN-LAST:event_purchaseInfoRecordsPanelMousePressed

    private void usersPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPanelMouseEntered
        setColor(usersPanel);
    }//GEN-LAST:event_usersPanelMouseEntered

    private void usersPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPanelMouseExited
        resetColor(usersPanel);
    }//GEN-LAST:event_usersPanelMouseExited

    private void usersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPanelMousePressed
        addUsersFrame();
    }//GEN-LAST:event_usersPanelMousePressed

    private void userLogsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLogsPanelMouseEntered
        setColor(userLogsPanel);
    }//GEN-LAST:event_userLogsPanelMouseEntered

    private void userLogsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLogsPanelMouseExited
        resetColor(userLogsPanel);
    }//GEN-LAST:event_userLogsPanelMouseExited

    private void userLogsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLogsPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLogsPanelMousePressed

    private void homePanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homePanelKeyPressed
        addHomeFrame();
    }//GEN-LAST:event_homePanelKeyPressed

    private void homePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseExited
        resetColor(homePanel);
    }//GEN-LAST:event_homePanelMouseExited

    private void homePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseEntered
        setColor(homePanel);
    }//GEN-LAST:event_homePanelMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JPanel prodPanel;
    private javax.swing.JPanel purchaseInfoRecordsPanel;
    private javax.swing.JPanel suppPanel;
    private javax.swing.JPanel userLogsPanel;
    private javax.swing.JPanel usersPanel;
    // End of variables declaration//GEN-END:variables
}
