/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DA.Users;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author New User
 */
public class LogsFrame extends javax.swing.JPanel {

    Home home;
    private static final String DELETED_RECORDS_FILE = "deleted_logs_records.txt";

    public LogsFrame(Home home) {
        initComponents();
        this.home = home;
        loadDataSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logsTable = new javax.swing.JTable();
        userButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 220, 201));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(logsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 99, 910, 410));

        userButton.setText("Users");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 67, -1, -1));

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });
        add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 68, 110, -1));

        jLabel1.setText("Search:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 50, 20));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 67, -1, -1));

        jLabel2.setBackground(new java.awt.Color(50, 57, 61));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("USER LOGS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        loadSearchData(searchField.getText());
    }//GEN-LAST:event_searchFieldKeyReleased

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        Users dellog = new Users();
        if (logsTable.getSelectedRow() < 0)
            JOptionPane.showMessageDialog(this, "Please select an entry from the table you wish to delete.");
        else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this log from the database?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                backupDeletedRow(logsTable.getSelectedRow());
                dellog.deleteLogDAO(Integer.parseInt(
                        logsTable.getValueAt(logsTable.getSelectedRow(), 0).toString()));
                loadDataSet();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        home.addUsersFrame();
    }//GEN-LAST:event_userButtonActionPerformed

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        if (searchField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_searchFieldKeyTyped
    public void loadDataSet() {
        try {
            Users logs = new Users();
            String[] columnNames = {"Log ID", "Name", "Login Time", "Logout Time"};
            logsTable.setModel(logs.buildTableModel(logs.getUserLogsDAO(), columnNames));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void loadSearchData(String searchText) {
        try {
            Users logs = new Users();
            String[] columnNames = {"Log ID", "Name", "Login Time", "Logout Time"};
            logsTable.setModel(logs.buildTableModel(logs.getLogsSearch(searchText), columnNames));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void backupDeletedRow(int selectedRow) {
        int columnCount = logsTable.getColumnCount();
        Object[] row = new Object[columnCount];
        for (int i = 0; i < columnCount; i++) {
            row[i] = logsTable.getValueAt(selectedRow, i);
        }
        // Save the row to the file
        saveDeletedRowToFile(row);
    }

    private void saveDeletedRowToFile(Object[] row) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(DELETED_RECORDS_FILE, true))) {
            StringBuilder sb = new StringBuilder();
            for (Object value : row) {
                sb.append(value).append("\t");
            }
            writer.write(sb.toString().trim());
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable logsTable;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
