/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DA.Prod;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;

public class PRecordsFrame extends javax.swing.JPanel {

    Home home;
    private static final String DELETED_RECORDS_FILE = "deleted_records.txt";

    public PRecordsFrame(Home home) {
        initComponents();
        this.home = home;
        loadDataSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pRecordsTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 220, 201));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pRecordsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pRecordsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pRecordsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 99, 890, 430));

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        salesButton.setText("Sales Records");
        salesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButtonActionPerformed(evt);
            }
        });
        add(salesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });
        add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 110, -1));

        jLabel1.setText("Search:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 20));

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel2.setBackground(new java.awt.Color(50, 57, 61));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("PURCHASE RECORDS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        Prod delrecord = new Prod();
        if (pRecordsTable.getSelectedRow() < 0)
            JOptionPane.showMessageDialog(null, "Please select a transaction from the table.");
        else {
            int opt = JOptionPane.showConfirmDialog(
                    null,
                    "Are you sure you want to delete this purchase?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                backupDeletedRow(pRecordsTable.getSelectedRow());
                delrecord.deletePurchaseDAO((int) pRecordsTable.getValueAt(pRecordsTable.getSelectedRow(), 0));
                loadDataSet();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed
    private boolean tableClicked = false;
    private void pRecordsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRecordsTableMouseClicked
        if (!tableClicked) { // Check if the table click event is enabled
            int row = pRecordsTable.getSelectedRow();
            int col = pRecordsTable.getColumnCount();
            Object[] data = new Object[col];

            for (int i = 0; i < col; i++) {
                data[i] = pRecordsTable.getValueAt(row, i);
            }

        } else {
            pRecordsTable.clearSelection();
        }

        tableClicked = !tableClicked;
    }//GEN-LAST:event_pRecordsTableMouseClicked

    private void salesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButtonActionPerformed
        home.addSalesRecordsFrame();
    }//GEN-LAST:event_salesButtonActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        loadSearchData(searchField.getText());
    }//GEN-LAST:event_searchFieldKeyReleased

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        if (searchField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_searchFieldKeyTyped

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        loadDataSet();
    }//GEN-LAST:event_refreshButtonActionPerformed

    public void loadDataSet() {
        try {
            Prod purchase = new Prod();
            String[] columnNames = {"Purchase ID", "Product Name", "Supplier", "Date", "Quantity", "Total Cost"};
            pRecordsTable.setDefaultEditor(Object.class, null);
            pRecordsTable.setModel(purchase.buildTableModel(purchase.getPurchaseInfo(), columnNames));
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    public void loadSearchData(String text) {
        try {
            Prod productDAO = new Prod();
            String[] columnNames = {"Purchase ID", "Product Name", "Supplier", "Date", "Quantity", "Total Cost"};
            pRecordsTable.setDefaultEditor(Object.class, null);
            pRecordsTable.setModel(productDAO.buildTableModel(productDAO.getPurchaseSearch(text), columnNames));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void backupDeletedRow(int selectedRow) {
        int columnCount = pRecordsTable.getColumnCount();
        Object[] row = new Object[columnCount];
        for (int i = 0; i < columnCount; i++) {
            row[i] = pRecordsTable.getValueAt(selectedRow, i);
        }
        // Save the row to the file
        saveDeletedRowToFile(row);
    }

    private void saveDeletedRowToFile(Object[] row) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(DELETED_RECORDS_FILE, true))) {
            StringBuilder sb = new StringBuilder();
            for (Object value : row) {
                sb.append(value).append("\t");
            }
            writer.write(sb.toString().trim());
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pRecordsTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton salesButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
