/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DA.Prod;
import DA.Supplier;
import DT.ProdDT;
import java.sql.*;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author New User
 */
public class ProductsFrame extends javax.swing.JPanel {

    ProdDT prod;
    Prod prd;
    int prodID;

    /**
     * Creates new form ProductsFrame
     */
    public ProductsFrame() {
        initComponents();
        loadComboBox();
        loadDataSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void loadSearchData(String text) {
        try {
            Prod productDAO = new Prod();
            String[] columnNames = {"Product ID", "Product Name", "Cost Price", "Sell Price", "Brand", "Stock"};
            productTable.setDefaultEditor(Object.class, null);
            productTable.setModel(productDAO.buildTableModel(productDAO.getProductSearch(text), columnNames));
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    public void loadComboBox() {
        try {
            Supplier supplierDAO = new Supplier();
            suppCbox.setModel(supplierDAO.setComboItems(supplierDAO.getQueryResult()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void loadDataSet() {
        try {
            Prod productDAO = new Prod();
            String[] columnNames = {"Product ID", "Product Name", "Cost Price", "Sell Price", "Brand", "Stock"};
            productTable.setDefaultEditor(Object.class, null);
            productTable.setModel(productDAO.buildTableModel(productDAO.getQueryResult(), columnNames));
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        suppCbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        costField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        sellField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        restockButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 220, 201));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Cost Price", "Sell Price", "Brand", "Stocks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 37, 630, 470));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Product Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suppCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(suppCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 101, -1));

        jLabel1.setText("Select Supplier:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 22));

        jLabel2.setText("Product Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 199, -1));

        jLabel3.setText("Cost Price:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setText("Sell Price:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setText("Brand:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setText("Quantity:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        costField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costFieldKeyTyped(evt);
            }
        });
        jPanel1.add(costField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        quantityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityFieldKeyTyped(evt);
            }
        });
        jPanel1.add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, -1));

        sellField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sellFieldKeyTyped(evt);
            }
        });
        jPanel1.add(sellField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, -1));

        brandField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                brandFieldKeyTyped(evt);
            }
        });
        jPanel1.add(brandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 200, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 60, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, -1));

        jLabel7.setText("Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        restockButton.setText("Restock");
        restockButton.setEnabled(false);
        restockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockButtonActionPerformed(evt);
            }
        });
        jPanel1.add(restockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, -1));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 60, -1));

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 60, -1));

        jScrollPane2.setViewportView(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleParent(this);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 37, 280, 470));

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });
        add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 9, 131, -1));

        jLabel8.setText("Search:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 12, -1, -1));

        jLabel9.setBackground(new java.awt.Color(50, 57, 61));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("PRODUCTS");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        prod = new ProdDT();
        prd = new Prod();
        if (nameField.getText().equals("") || jDateChooser1.getDate() == null
                || quantityField.getText().equals("") || costField.getText().equals("")
                || sellField.getText().equals("") || brandField.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter all the required details.");
        else {
            try {
                ResultSet resultSet = prd.getProdName(nameField.getText());
                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(null, "This product is already added in the inventory.");

                } else {
                    prod.setProdName(nameField.getText());
                    prod.setCostPrice(Double.parseDouble(costField.getText()));
                    prod.setSellPrice(Double.parseDouble(sellField.getText()));
                    prod.setBrand(brandField.getText());
                    prod.setQuantity(Integer.parseInt(quantityField.getText()));
                    prd.addFunction(prod);
                    prod.setSuppName(suppCbox.getSelectedItem().toString());
                    String name = prod.getSuppName();
                    String id = prd.getSuppID(name);
                    prod.setSuppID(Integer.parseInt(id));
                    String pid = prd.getProdID(nameField.getText());
                    prod.setProdID(Integer.parseInt(pid));
                    prod.setDate(jDateChooser1.getDate().toString());
                    Double costPrice = Double.valueOf(costField.getText());
                    Double totalCost = costPrice * Integer.valueOf(quantityField.getText());
                    prod.setTotalCost(totalCost);
                    prd.addPurchaseDAO(prod);
                    loadDataSet();
                    clear();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed
    private boolean tableClicked = false;
    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        if (!tableClicked) { // Check if the table click event is enabled
            int row = productTable.getSelectedRow();
            int col = productTable.getColumnCount();
            Object[] data = new Object[col];

            for (int i = 0; i < col; i++) {
                data[i] = productTable.getValueAt(row, i);
            }
            prodID = (Integer) data[0];
            nameField.setText((String) data[1]);
            Double costValue = (Double) data[2];
            costField.setText(String.valueOf(costValue));
            Double sellValue = (Double) data[3];
            sellField.setText(String.valueOf(sellValue));
            brandField.setText((String) data[4]);
            restockButton.setEnabled(true);
        } else {
            productTable.clearSelection();
            clear();
        }

        tableClicked = !tableClicked;
    }//GEN-LAST:event_productTableMouseClicked

    private void restockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockButtonActionPerformed
        prod = new ProdDT();
        prd = new Prod();
        String userInput = JOptionPane.showInputDialog(null, "Enter the quantity of the product:");
        if (userInput == null) {
            return;
        }
        boolean validInput = false;

        try {
            int quantity = Integer.parseInt(userInput);
            prod.setQuantity(quantity + prd.getStock(nameField.getText()));
            prod.setRestock(quantity);
            validInput = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input! Please enter a valid number.");
        }

        if (validInput) {
            try {
                Supplier supplierDAO = new Supplier();
                JComboBox<String> suppCbox = new JComboBox<>(supplierDAO.setComboItems(supplierDAO.getQueryResult()));

                int choice = JOptionPane.showOptionDialog(
                        null,
                        suppCbox,
                        "Select a Supplier",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        null,
                        null
                );

                if (choice == JOptionPane.OK_OPTION) {
                    String selectedSupplier = (String) suppCbox.getSelectedItem();
                    prod.setSuppName(selectedSupplier);
                    String name = prod.getSuppName();
                    String id = prd.getSuppID(name);
                    prod.setSuppID(Integer.parseInt(id));

                    String pid = prd.getProdID(nameField.getText());
                    prod.setProdID(Integer.parseInt(pid));

                    ZonedDateTime currentDateTime = ZonedDateTime.now();
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("E MMM dd HH:mm:ss z yyyy");
                    String formattedDateTime = currentDateTime.format(formatter);
                    prod.setDate(formattedDateTime);

                    Double costPrice = Double.valueOf(costField.getText());
                    Double totalCost = costPrice * prod.getRestock();
                    prod.setTotalCost(totalCost);

                    prd.addRestockPurchase(prod);

                    prod.setProdName(nameField.getText());
                    prod.setCostPrice(Double.parseDouble(costField.getText()));
                    prod.setSellPrice(Double.parseDouble(sellField.getText()));
                    prod.setBrand(brandField.getText());
                    prd.addRestock(prod);

                    loadDataSet();
                    restockButton.setEnabled(false);
                    clear();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_restockButtonActionPerformed

    private void clear() {
        nameField.setText("");
        costField.setText("");
        sellField.setText("");
        brandField.setText("");
        quantityField.setText("");
        jDateChooser1.setDate(null);
        restockButton.setEnabled(false);
    }
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        loadSearchData(searchField.getText());
    }//GEN-LAST:event_searchFieldKeyReleased

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (productTable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Please select an entry to edit from the table.");
        } else {

            if (nameField.getText().equals("") || costField.getText().equals("") || sellField.getText().equals("")
                    || brandField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter all the required details.");
            } else {
                Prod prodedit = new Prod();
                ProdDT newprod = new ProdDT();
                newprod.setProdID(prodID);
                newprod.setProdName(nameField.getText());
                newprod.setCostPrice(Double.parseDouble(costField.getText()));
                newprod.setSellPrice(Double.parseDouble(sellField.getText()));
                newprod.setBrand(brandField.getText());
                prodedit.editProdDAO(newprod);
                loadDataSet();
                clear();
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        if (searchField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_searchFieldKeyTyped

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        if (nameField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_nameFieldKeyTyped

    private void quantityFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityFieldKeyTyped
        char c = evt.getKeyChar();
        String text = quantityField.getText();

        // Check if the input character is a digit
        if (!Character.isDigit(c)) {
            evt.consume(); // Ignore the event if it's not a digit
            return;
        }

        // Limit to 5 characters
        if (text.length() >= 5) {
            evt.consume(); // Ignore the event if there are already 5 characters
            return;
        }
    }//GEN-LAST:event_quantityFieldKeyTyped

    private void costFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costFieldKeyTyped
        String text = costField.getText() + evt.getKeyChar();

        if (text.length() > 8 || !text.matches("\\d*(\\.\\d{0,2})?")) {
            evt.consume();
        }
    }//GEN-LAST:event_costFieldKeyTyped

    private void sellFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellFieldKeyTyped
        String text = sellField.getText() + evt.getKeyChar();

        if (text.length() > 8 || !text.matches("\\d*(\\.\\d{0,2})?")) {
            evt.consume();
        }
    }//GEN-LAST:event_sellFieldKeyTyped

    private void brandFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandFieldKeyTyped
        if (brandField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_brandFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField brandField;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField costField;
    private javax.swing.JButton editButton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton restockButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField sellField;
    private javax.swing.JComboBox<String> suppCbox;
    // End of variables declaration//GEN-END:variables
}
