/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DA.Supplier;
import DT.SupplierDT;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author New User
 */
public class SuppliersFrame extends javax.swing.JPanel {

    /**
     * Creates new form SuppliersFrame
     */
    int suppID;

    public SuppliersFrame() {
        initComponents();
        loadDataSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        suppTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 220, 201));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suppTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        suppTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(suppTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, 470));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Supplier Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Supplier Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setText("Location:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setText("Contact:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 170, -1));

        locationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                locationFieldKeyTyped(evt);
            }
        });
        jPanel1.add(locationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, -1));

        contactField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactFieldKeyTyped(evt);
            }
        });
        jPanel1.add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, -1));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 260, 467));

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });
        add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 8, 131, -1));

        jLabel4.setText("Search:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 11, -1, -1));

        jLabel5.setBackground(new java.awt.Color(50, 57, 61));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SUPPLIERS");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (nameField.getText().equals("") || locationField.getText().equals("") || contactField.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Please enter all the required details.");
        else {
            SupplierDT supplierDTO = new SupplierDT();
            Supplier supp = new Supplier();
            supplierDTO.setFullName(nameField.getText());
            supplierDTO.setLocation(locationField.getText());
            supplierDTO.setPhone(contactField.getText());
            supp.addSupplierDAO(supplierDTO);
            loadDataSet();
            clear();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (suppTable.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Please select an entry to edit from the table.");
        } else {

            if (nameField.getText().equals("") || locationField.getText().equals("") || contactField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter all the required details.");
            } else {
                SupplierDT supplierDTO = new SupplierDT();
                Supplier supp = new Supplier();
                supplierDTO.setSuppID(suppID);
                supplierDTO.setFullName(nameField.getText());
                supplierDTO.setLocation(locationField.getText());
                supplierDTO.setPhone(contactField.getText());
                supp.editSupplierDAO(supplierDTO);
                loadDataSet();
                clear();
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        loadSearchData(searchField.getText());
    }//GEN-LAST:event_searchFieldKeyReleased
    private boolean tableClicked = false;
    private void suppTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppTableMouseClicked
        if (!tableClicked) {
            int row = suppTable.getSelectedRow();
            int col = suppTable.getColumnCount();
            Object[] data = new Object[col];

            for (int i = 0; i < col; i++) {
                data[i] = suppTable.getValueAt(row, i);
            }
            suppID = (int) data[0];
            nameField.setText((String) data[1]);
            locationField.setText((String) data[2]);
            contactField.setText((String) data[3]);
        } else {
            suppTable.clearSelection();
            clear();
        }
        tableClicked = !tableClicked;
    }//GEN-LAST:event_suppTableMouseClicked

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        if (searchField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_searchFieldKeyTyped

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        if (nameField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_nameFieldKeyTyped

    private void locationFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationFieldKeyTyped
        if (locationField.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_locationFieldKeyTyped

    private void contactFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactFieldKeyTyped
        char c = evt.getKeyChar();
        String text = contactField.getText();

        // Check if the input character is a digit
        if (!Character.isDigit(c)) {
            evt.consume(); // Ignore the event if it's not a digit
            return;
        }

        // Limit to 5 characters
        if (text.length() >= 11) {
            evt.consume(); // Ignore the event if there are already 5 characters
            return;
        }
    }//GEN-LAST:event_contactFieldKeyTyped

    public void clear() {
        nameField.setText("");
        locationField.setText("");
        contactField.setText("");
    }

    public void loadDataSet() {
        try {
            Supplier supplierDAO = new Supplier();
            String[] customColumnNames = {"Supplier ID", "Full Name", "Location", "Contact"};
            suppTable.setDefaultEditor(Object.class, null);
            suppTable.setModel(supplierDAO.buildTableModel(supplierDAO.getQueryResult(), customColumnNames));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void loadSearchData(String text) {
        try {
            Supplier supplierDAO = new Supplier();
            String[] customColumnNames = {"Supplier ID", "Full Name", "Location", "Contact"};
            suppTable.setDefaultEditor(Object.class, null);
            suppTable.setModel(supplierDAO.buildTableModel(supplierDAO.getSearchResult(text), customColumnNames));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField contactField;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locationField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable suppTable;
    // End of variables declaration//GEN-END:variables
}
